spring.application.name=APIGateway

server.port=8080

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webflux.routes[0].id=customer-route
spring.cloud.gateway.server.webflux.routes[0].uri=lb://CustomerMicroservice
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/customers/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.name=customerCircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.fallbackUri=forward:/fallback/customer


spring.cloud.gateway.server.webflux.routes[1].id=product-route
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ProductMicroservice
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=productCircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/fallback/product

spring.cloud.gateway.server.webflux.routes[2].id=order-route
spring.cloud.gateway.server.webflux.routes[2].uri=lb://OrderMicroservice
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.name=orderCircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.fallbackUri=forward:/fallback/order

management.endpoints.web.exposure.include=*

resilience4j.circuitbreaker.instances.customerCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.customerCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.customerCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.customerCircuitBreaker.sliding-window-size=10

resilience4j.circuitbreaker.instances.productCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.productCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.productCircuitBreaker.sliding-window-size=10

resilience4j.circuitbreaker.instances.orderCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.orderCircuitBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.orderCircuitBreaker.sliding-window-size=10